# Lab | Pandas

In this lab, we will be working with the customer data from an insurance company, which can be found in the CSV file located at the following link: https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

The data includes information such as customer ID, state, gender, education, income, and other variables that can be used to perform various analyses.

Throughout the lab, we will be using the pandas library in Python to manipulate and analyze the data. Pandas is a powerful library that provides various data manipulation and analysis tools, including the ability to load and manipulate data from a variety of sources, including CSV files.

### Data Description

- Customer - Customer ID

- ST - State where customers live

- Gender - Gender of the customer

- Education - Background education of customers 

- Customer Lifetime Value - Customer lifetime value(CLV) is the total revenue the client will derive from their entire relationship with a customer. In other words, is the predicted or calculated value of a customer over their entire duration as a policyholder with the insurance company. It is an estimation of the net profit that the insurance company expects to generate from a customer throughout their relationship with the company. Customer Lifetime Value takes into account factors such as the duration of the customer's policy, premium payments, claim history, renewal likelihood, and potential additional services or products the customer may purchase. It helps insurers assess the long-term profitability and value associated with retaining a particular customer.

- Income - Customers income

- Monthly Premium Auto - Amount of money the customer pays on a monthly basis as a premium for their auto insurance coverage. It represents the recurring cost that the insured person must pay to maintain their insurance policy and receive coverage for potential damages, accidents, or other covered events related to their vehicle.

- Number of Open Complaints - Number of complaints the customer opened

- Policy Type - There are three type of policies in car insurance (Corporate Auto, Personal Auto, and Special Auto)

- Vehicle Class - Type of vehicle classes that customers have Two-Door Car, Four-Door Car SUV, Luxury SUV, Sports Car, and Luxury Car

- Total Claim Amount - the sum of all claims made by the customer. It represents the total monetary value of all approved claims for incidents such as accidents, theft, vandalism, or other covered events.

External Resources: https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9

## Challenge 1: Understanding the data

In this challenge, you will use pandas to explore a given dataset. Your task is to gain a deep understanding of the data by analyzing its characteristics, dimensions, and statistical properties.

- Identify the dimensions of the dataset by determining the number of rows and columns it contains.
- Determine the data types of each column and evaluate whether they are appropriate for the nature of the variable. You should also provide suggestions for fixing any incorrect data types.
- Identify the number of unique values for each column and determine which columns appear to be categorical. You should also describe the unique values of each categorical column and the range of values for numerical columns, and give your insights.
- Compute summary statistics such as mean, median, mode, standard deviation, and quartiles to understand the central tendency and distribution of the data for numerical columns. You should also provide your conclusions based on these summary statistics.
- Compute summary statistics for categorical columns and providing your conclusions based on these statistics.

In [45]:
# Your code heret
import pandas as pd

insurance_data = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv")

insurance_data.head(10)

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323
5,OC83172,Oregon,F,Bachelor,825629.78%,62902.0,69.0,1/0/00,Personal Auto,Two-Door Car,159.383042
6,XZ87318,Oregon,F,College,538089.86%,55350.0,67.0,1/0/00,Corporate Auto,Four-Door Car,321.600000
7,CF85061,Arizona,M,Master,721610.03%,0.0,101.0,1/0/00,Corporate Auto,Four-Door Car,363.029680
8,DY87989,Oregon,M,Bachelor,2412750.40%,14072.0,71.0,1/0/00,Corporate Auto,Four-Door Car,511.200000
9,BQ94931,Oregon,F,College,738817.81%,28812.0,93.0,1/0/00,Special Auto,Four-Door Car,425.527834

**- Identify the dimensions of the dataset by determining the number of rows and columns it contains.**

In [43]:
insurance_data.shape

(4008, 11)

**- Determine the data types of each column and evaluate whether they are appropriate for the nature of the variable. You should also provide suggestions for fixing any incorrect data types.**

In [41]:
insurance_data.dtypes

Customer                      object
ST                            object
GENDER                        object
Education                     object
Customer Lifetime Value       object
Income                       float64
Monthly Premium Auto         float64
Number of Open Complaints     object
Policy Type                   object
Vehicle Class                 object
Total Claim Amount           float64
dtype: object

In [46]:
insurance_data["Number of Open Complaints"].value_counts()

Number of Open Complaints
1/0/00    830
1/1/00    138
1/2/00     50
1/3/00     34
1/4/00     13
1/5/00      6
Name: count, dtype: int64

Suggestions on datatypes:
1. Customer Lifetime Value: This column's datatype is object, it should be i think float or int, also before converting it to int/float we have to remove the % sign, because it don't seem correct percentage and without removing it we can not covert it to numerical
2. Number of Open Complaints: Need to see into this column the value before 1st slash and last slash are same for all unique number_of_complaints column values. So i think we need to remove the part between two slashes and remove the rest and convert column into int

**- Identify the number of unique values for each column and determine which columns appear to be categorical. You should also describe the unique values of each categorical column and the range of values for numerical columns, and give your insights.**

In [ ]:
# This seems id column so all values will be unique
insurance_data["Customer"].value_counts()

Customer
MY31220    1
RB50392    1
QZ44356    1
AI49188    1
WW63253    1
          ..
FL50705    1
WC83389    1
OE15005    1
FV94802    1
BW63560    1
Name: count, Length: 1071, dtype: int64

In [ ]:
insurance_data["Customer"].duplicated().sum()

np.int64(2936)

Customer has duplicated rows..so we need to check if we are thinking if it is primary key

In [56]:
insurance_data["ST"].value_counts()

ST
Oregon        320
California    211
Arizona       186
Cali          120
Nevada         98
Washington     81
WA             30
AZ             25
Name: count, dtype: int64

here for state values it seems:
"California" and "Cali" : same state
"Washington" and "WA" : same state
"Arizona" and "AZ" : same state

In [57]:
insurance_data["GENDER"].value_counts()

GENDER
F         457
M         413
Male       39
female     28
Femal      17
Name: count, dtype: int64

here for gender it seems:
"Male" and "M" : are same
"female" and "F"  and "Femal": are same

In [58]:
insurance_data["Education"].value_counts()

Education
Bachelor                324
College                 313
High School or Below    296
Master                   94
Doctor                   37
Bachelors                 7
Name: count, dtype: int64

here for Education it seems:
"Bachelor" and "Bachelors" : same

In [59]:
insurance_data["Customer Lifetime Value"].value_counts()

Customer Lifetime Value
251459.20%    4
445811.34%    4
578018.22%    3
684615.03%    3
477294.38%    3
             ..
251753.36%    1
532667.77%    1
260027.21%    1
853479.28%    1
882883.50%    1
Name: count, Length: 1027, dtype: int64

Customer Lifetime Value is Numerical column with invalid % sign

In [60]:
insurance_data["Income"].value_counts()

Income
0.0        252
43860.0      4
17622.0      4
20993.0      3
51066.0      3
          ...
69417.0      1
38644.0      1
63209.0      1
16061.0      1
34990.0      1
Name: count, Length: 774, dtype: int64

Income is numerical column

In [62]:
insurance_data["Monthly Premium Auto"].value_counts()

Monthly Premium Auto
65.0     47
63.0     39
71.0     37
67.0     37
73.0     37
         ..
285.0     1
148.0     1
141.0     1
197.0     1
199.0     1
Name: count, Length: 132, dtype: int64

Monthly Premium Auto is numerical Column

In [63]:
insurance_data["Number of Open Complaints"].value_counts()

Number of Open Complaints
1/0/00    830
1/1/00    138
1/2/00     50
1/3/00     34
1/4/00     13
1/5/00      6
Name: count, dtype: int64

Number of Open Complaints: with incorrect data format
Technically : numerical (discrete)
Practically : often treated as categorical or ordinal

In [64]:
insurance_data["Policy Type"].value_counts()

Policy Type
Personal Auto     780
Corporate Auto    234
Special Auto       57
Name: count, dtype: int64

Policy Type:Categorical, correct data

In [65]:
insurance_data["Vehicle Class"].value_counts()

Vehicle Class
Four-Door Car    576
Two-Door Car     205
SUV              199
Sports Car        57
Luxury SUV        20
Luxury Car        14
Name: count, dtype: int64

Vehicle Class: Categorical

In [66]:
insurance_data["Total Claim Amount"].value_counts()

Total Claim Amount
321.600000    19
331.200000    15
312.000000    14
350.400000    14
316.800000    12
              ..
171.325856     1
249.085887     1
30.874869      1
361.455219     1
42.096415      1
Name: count, Length: 761, dtype: int64

Total Claim Amount:
Numerical data

In [69]:
insurance_data.describe(include='all')

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
count,1071,1071,954,1071,1068,1071.000000,1071.000000,1071,1071,1071,1071.000000
unique,1071,8,5,6,1027,NaN,NaN,6,3,6,NaN
top,MY31220,Oregon,F,Bachelor,251459.20%,NaN,NaN,1/0/00,Personal Auto,Four-Door Car,NaN
freq,1,320,457,324,4,NaN,NaN,830,780,576,NaN
mean,NaN,NaN,NaN,NaN,NaN,39295.701214,193.234360,NaN,NaN,NaN,404.986909
std,NaN,NaN,NaN,NaN,NaN,30469.427060,1601.190369,NaN,NaN,NaN,293.027260
min,NaN,NaN,NaN,NaN,NaN,0.000000,61.000000,NaN,NaN,NaN,0.382107
25%,NaN,NaN,NaN,NaN,NaN,14072.000000,68.000000,NaN,NaN,NaN,202.157702
50%,NaN,NaN,NaN,NaN,NaN,36234.000000,83.000000,NaN,NaN,NaN,354.729129
75%,NaN,NaN,NaN,NaN,NaN,64631.000000,109.500000,NaN,NaN,NaN,532.800000
max,NaN,NaN,NaN,NaN,NaN,99960.000000,35354.000000,NaN,NaN,NaN,2893.239678

Numerical:
    1. Customer Lifetime value
    2. Income 
    3. Monthly premium Auto
    4. Total Claim amount

Categorical:
    1. Customer
    2. Gender
    3. Education
    4. Number of Open Complaints
    5. Policy Type
    6. Vehicle Class

In [71]:
insurance_data.dtypes

Customer                      object
ST                            object
GENDER                        object
Education                     object
Customer Lifetime Value       object
Income                       float64
Monthly Premium Auto         float64
Number of Open Complaints     object
Policy Type                   object
Vehicle Class                 object
Total Claim Amount           float64
dtype: object

In [72]:
insurance_data["Customer Lifetime Value"] = pd.to_numeric(
    insurance_data["Customer Lifetime Value"].str.replace("%", "", regex=False),
    errors="coerce"
)

In [74]:
insurance_data.describe()

,Customer Lifetime Value,Income,Monthly Premium Auto,Total Claim Amount
count,1.068000e+03,1071.000000,1071.000000,1071.000000
mean,7.936903e+05,39295.701214,193.234360,404.986909
std,6.434784e+05,30469.427060,1601.190369,293.027260
min,2.004351e+05,0.000000,61.000000,0.382107
25%,4.034080e+05,14072.000000,68.000000,202.157702
50%,5.881742e+05,36234.000000,83.000000,354.729129
75%,8.962872e+05,64631.000000,109.500000,532.800000
max,5.816655e+06,99960.000000,35354.000000,2893.239678

- 0 income value does not seem valid
- to check outlies we need to create bins for ranges and then check if outliers present

In [75]:
insurance_data.describe(include="object")

,Customer,ST,GENDER,Education,Number of Open Complaints,Policy Type,Vehicle Class
count,1071,1071,954,1071,1071,1071,1071
unique,1071,8,5,6,6,3,6
top,MY31220,Oregon,F,Bachelor,1/0/00,Personal Auto,Four-Door Car
freq,1,320,457,324,830,780,576

## Challenge 2: analyzing the data

### Exercise 1

The marketing team wants to know the top 5 less common customer locations. Create a pandas Series object that contains the customer locations and their frequencies, and then retrieve the top 5 less common locations in ascending order.

In [12]:
# Your code here
location_series = insurance_data["ST"]
print("\n All locations with their frequencies: ")
print(location_series.value_counts())   

print("\n Top 5 less common locations with their frequencies: ")
print(location_series.value_counts(ascending=True).head(5))

 All locations with their frequencies:
ST
Oregon        320
California    211
Arizona       186
Cali          120
Nevada         98
Washington     81
WA             30
AZ             25
Name: count, dtype: int64

 Top 5 less common locations with their frequencies:
ST
AZ             25
WA             30
Washington     81
Nevada         98
Cali          120
Name: count, dtype: int64

### Exercise 2

The sales team wants to know the total number of policies sold for each type of policy. Create a pandas Series object that contains the policy types and their total number of policies sold, and then retrieve the policy type with the highest number of policies sold.

*Hint:*
- *Using value_counts() method simplifies this analysis.*
- *Futhermore, there is a method that returns the index of the maximum value in a column or row.*

In [24]:
# Your code here
policy_type_series = insurance_data["Policy Type"]

max_policy_cnt = policy_type_series.value_counts().max()

print("\nPolicy type with the highest number of policies sold:")
print(policy_type_series[max_policy_cnt], "with", max_policy_cnt, "count")

Policy type with the highest number of policies sold:
Personal Auto with 780 count

### Exercise 3

The sales team wants to know if customers with Personal Auto have a lower income than those with Corporate Auto. How does the average income compare between the two policy types?

- Use *loc* to create two dataframes: one containing only Personal Auto policies and one containing only Corporate Auto policies.
- Calculate the average income for each policy.
- Print the results.

In [39]:
# Your code here

personal_auto_policies = insurance_data.loc[insurance_data["Policy Type"]=="Personal Auto"]
Corporate_auto_policies = insurance_data.loc[insurance_data["Policy Type"]=="Corporate Auto"]

personal_auto_policies_avg = (personal_auto_policies["Income"]).mean()
print("Average income of customers with Policy type Personal Auto:" ,personal_auto_policies_avg)


Corporate_auto_policies_avg = (Corporate_auto_policies["Income"]).mean()
print("\nAverage income of customers with Policy type Corporate Auto:" ,Corporate_auto_policies_avg)

Average income of customers with Policy type Personal Auto: 38180.69871794872

Average income of customers with Policy type Corporate Auto: 41390.31196581197

### Bonus: Exercise 4

Your goal is to identify customers with a high policy claim amount.

Instructions:

- Review again the statistics for total claim amount to gain an understanding of the data.
- To identify potential areas for improving customer retention and profitability, we want to focus on customers with a high policy claim amount. Consider customers with a high policy claim amount to be those in the top 25% of the total claim amount. Create a pandas DataFrame object that contains information about customers with a policy claim amount greater than the 75th percentile.
- Use DataFrame methods to calculate summary statistics about the high policy claim amount data.

*Note: When analyzing data, we often want to focus on certain groups of values to gain insights. Percentiles are a useful tool to help us define these groups. A percentile is a measure that tells us what percentage of values in a dataset are below a certain value. For example, the 75th percentile represents the value below which 75% of the data falls. Similarly, the 25th percentile represents the value below which 25% of the data falls. When we talk about the top 25%, we are referring to the values that fall above the 75th percentile, which represent the top quarter of the data. On the other hand, when we talk about the bottom 25%, we are referring to the values that fall below the 25th percentile, which represent the bottom quarter of the data. By focusing on these groups, we can identify patterns and trends that may be useful for making decisions and taking action.*

*Hint: look for a method that gives you the percentile or quantile 0.75 and 0.25 for a Pandas Series.*

*Hint 2: check `Boolean selection according to the values of a single column` in https://towardsdatascience.com/filtering-data-frames-in-pandas-b570b1f834b9*

In [77]:
# Your code here
insurance_data["Total Claim Amount"].describe()

count    1071.000000
mean      404.986909
std       293.027260
min         0.382107
25%       202.157702
50%       354.729129
75%       532.800000
max      2893.239678
Name: Total Claim Amount, dtype: float64

In [88]:
q3 = insurance_data["Total Claim Amount"].quantile(0.75)
print(q3)

top_claim_customers = insurance_data[insurance_data["Total Claim Amount"] >= q3]
top_claim_customers.shape

532.8

(273, 12)